import Head from "next/head";
import { ReactElement } from "react";
import { Navbar } from "./Navbar";
import { Container, Grid } from "@mui/material";

interface PrincipalLayoutProps {
  children: ReactElement;
}

export const PrincipalLayout = ({ children }: PrincipalLayoutProps) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Navbar />
      </nav>

      <main>
        <Container maxWidth={false}>
          <Grid
            container
            display={"flex"}
            justifyContent={"center"}
            mt={2}
            mb={2}
          >
            <Grid item xs={12} md={11}>
              {children}
            </Grid>
          </Grid>
        </Container>
      </main>
    </>
  );
};
